### ISSUE TITLE
Evolution Letters: checklist of things to do (revision due by Sept. 9)

### ISSUE THREAD

**Issue by jennahamlin** [jennahamlin/tomato.introgression#5]
- [x] map colored by species and with accession designation (Jenna) 

- [ ] Consensus phylogeny (at least of species used here) - @mhibbins  - will this get inferred in any of the below methods? or should I build a tree

- [x] estimated D stat with bootstrap for significance: methods and results (Mark)

- [ ] estimate admixture proportion with phylonet: methods and results (Mark)

- [ ] estimate direction of admixture with Hibbins and Hahn (2019) method: methods and results (Mark)

- [x] clean up figure 2 and 3 (Jenna)

- [ ] replot figure 4 with updated estimates of D (Jenna)

- [x] minor corrects (Jenna)

**Comment by mhibbins** [comment]
None of the stuff I will be doing involves building a consensus tree, so you can go ahead and do that (although I am happy to if you can't find the time).

**Comment by jennahamlin** [comment]
@mhibbins  - okay i am attempting to build a phylogeny with RAxML -
